set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-position bottom
set -g status-interval 1
set -g status-justify left

set -g status-style "bg=#002B36,fg=#c0caf5" 

set -g status-left-length 100
set -g status-left "#[bg=#268BD2,fg=#15161e,bold] >_ #[bg=#b58900,fg=#268BD2]#[bg=#b58900,fg=#15161e,bold] 󰍹 #S #[bg=#002B36,fg=#b58900]"

set -g window-status-format "#[bg=#15161e,fg=#a9b1d6]  #I #W  "

set -g window-status-current-format "#[bg=#002B36,fg=#CB4B16] #[bg=#CB4B16,fg=#15161e,bold]#I  #W#[bg=#002B36,fg=#CB4B16]"

set -g status-right-length 100
set -g status-right "#[bg=#002B36,fg=#859900]#[bg=#859900,fg=#15161e,bold]  #{b:pane_current_path} #[bg=#859900,fg=#dc322f]#[bg=#dc322f,fg=#15161e] 󱇫 #(awk -F= '/^ID=/{print \$2}' /etc/os-release | tr -d '\"')"
